# Stage 1: Build client (ví dụ dùng Node.js)
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 

# Stage 2: Build image nginx
FROM nginx:alpine
# Copy file build từ stage builder vào thư mục nginx
COPY --from=builder /app/dist /usr/share/nginx/html
# Copy file cấu hình nginx nếu cần, ví dụ:
COPY ./production/production.default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]