version: "3.8"

services:
  nginx:
    build:
      context: "./client"
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html 
      - ./client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server  
    networks:
      - app-network

  server:
    build:
      context: "./server"
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    env_file:
      - .env.production
    networks:
      - app-network
    ports:
      - "8017:8017"
    expose:
      - 8017
      
networks:
  app-network:
    driver: bridge  # Đảm bảo cả 2 container có thể giao tiếp
