version: "3.8"

services:
  nginx:
    image: luuquangtri95/webapp_banhtrangchutruy_client:latest
    # build:
      # context: "./client"
      # dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./client/dist:/usr/share/nginx/html 
      - ./production/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server  
    networks:
      - app-network

  server:
    image: luuquangtri95/webapp_banhtrangchutruy_server:latest
    # build:
    #   context: "./server"
    #   dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    env_file:
      - .env.production
    networks:
      - app-network
    ports:
      - "8017:8017"
    expose:
      - 8017
      
networks:
  app-network:
    driver: bridge  # Đảm bảo cả 2 container có thể giao tiếp
