version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8017:8000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    env_file:
      - ./server/.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 