version: "3.8"

services:
  nginx:
    build:
      context: "./client"
      dockerfile: Dockerfile.prod
    ports:
      - "8017:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./client/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server  # Đảm bảo Nginx chạy sau khi server đã khởi động
    networks:
      - app-network  # Đặt nginx vào cùng network với server

  server:
    build:
      context: "./server"
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    env_file:
      - .env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Đảm bảo cả 2 container có thể giao tiếp
