version: '3.8'

services:
  client:
    build: 
      context: "./client"
      dockerfile: "Dockerfile.dev"
    ports:
      - "5173:5173"  # Port cho Vite dev server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - server

  server:
    build:
      context: "./server"
      dockerfile: "Dockerfile.dev"
    ports:
      - "8017:8017"  # Map port 8017 ra ngoài
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - HOST=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 