name: Build and Deploy Docker

on:
  push:
    branches: [ "master" ]
    # Hoặc bạn có thể dùng: branches: [ "main", "develop" ] nếu muốn trigger trên nhiều nhánh

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile         # Dockerfile nằm ở thư mục gốc (điều chỉnh nếu khác)
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy:latest
          # Bạn có thể thêm :v1.0.0,... nếu muốn versioning

  deploy:
    # deploy job sẽ chỉ chạy khi job build-and-push thành công
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to server (optional)
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/var/www/chutruyfood"  # Thư mục trên server, tùy chỉnh theo ý bạn

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Đăng nhập Docker Hub trên server (để pull image)
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

            # 2. Pull image mới nhất
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

            # 3. Di chuyển vào thư mục chứa docker-compose.yml
            cd /var/www/chutruyfood

            # 4. Chạy docker-compose (đảm bảo file docker-compose.yml dùng image đã push)
            docker-compose up -d
