name: Build and Deploy Docker

on:
  push:
    branches: [ "master" ]  # Hoặc "master" tùy repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production #chọn env trên github
    steps:
      # Lấy code về
      - name: Check out code
        uses: actions/checkout@v3

      # Thiết lập buildx để build Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Đăng nhập Docker Hub (dùng token hoặc password)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build và push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy:latest
          # Có thể thêm :v1.0.0,... nếu muốn versioning

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # (Tùy chọn) Copy docker-compose.yml lên server
      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/var/www/chutruyfood"  # thư mục trên server

      # SSH vào server, pull image, chạy docker-compose
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Đăng nhập Docker Hub trên server
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            # 2. Pull image mới
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy:latest

            # 3. Vào thư mục chứa docker-compose.yml
            cd /var/www/chutruyfood

            #4. build client
            npm run build:client

            # 5. Chạy docker-compose để khởi động container
            docker-compose up -d --build
