name: Build and Deploy Docker

on:
  push:
    branches: [ "master" ]  # Hoặc "main" tùy theo nhánh bạn dùng

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production  # Nếu bạn dùng Environment-level, nhớ tạo "production" trong repo Settings
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push Client Image
      - name: Build & Push Client
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile.prod
          build-args: |
            VITE_API_URL= ${{ vars.VITE_API_URL }}
          tags: ${{ vars.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy_client:latest
          push: true

      # Build & Push Server Image
      - name: Build & Push Server
        uses: docker/build-push-action@v3
        with:
          context: ./server
          file: ./server/Dockerfile.prod
          tags: ${{ vars.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy_server:latest
          push: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/var/www/chutruyfood"  # Nơi lưu file trên server

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. Đăng nhập Docker Hub
            docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            # 2. Pull 2 image mới
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy_client:latest
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/webapp_banhtrangchutruy_server:latest

            # 3. Vào thư mục chứa docker-compose.yml
            cd /var/www/chutruyfood

            #4 pull code
            git checkout .
            git pull

            # # 4. build client
            # npm run build:client

            docker compose down

            # 5. Khởi chạy container (hoặc cập nhật nếu đã có)
            docker compose up -d --build
